apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vzz2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vzz2
    app.kubernetes.io/part-of: integ-app-wtod
  name: hacbs-test-project-vzz2
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vzz2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vzz2
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/nbe-e2e-hmcq-tenant/integ-app-wtod/hacbs-test-project-vzz2@sha256:fdcf29b74601c862be1c8d25a633222f6039bfd9107b8984b7a20819d7fcddf2
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
