apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-vzz2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/nbe-e2e-hmcq-tenant/integ-app-wtod/hacbs-test-project-vzz2@sha256:fdcf29b74601c862be1c8d25a633222f6039bfd9107b8984b7a20819d7fcddf2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
